
spring:
  datasource:
    name: cjf  #????
    url: jdbc:mysql://localhost:3306/cjf #url
    username: root  #???
    password: 13326chen  #??
    driver-class-name: com.mysql.jdbc.Driver  #???????
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#      exclude: WEB-INF/**



mybatis:
  mapper-locations: classpath:mapper/*.xml  #??????
  type-aliases-package: com.example.test.bean #?????



